[WIP] Reporte: 25 de Julio de 2018 - ¿Correos de Chile?
leosoto/incidentes-seguridad-chile pull request #1
Opened 2018-08-13 02:46 UTC by paparga

Marco el reporte como WIP porque aun está siendo investigado por la [justicia](http://www.sbif.cl/sbifweb/servlet/Noticia?indice=2.1&idContenido=12162).

2018-08-13 12:36 UTC, leosoto requested changes
¡Gracias! Es un super buen primer reporte para un problema de seguridad cuyo verdadero origen aún sigue en la nebulosa.

Sugiero que saquemos a correos de esto mientras no hayan pruebas claras de que la info salió de ahí (pero bienvenido a discutirme si dichas pruebas ya existen). 

De todas formas aunque varios campos queden en estado "Desconocido" (la empresa) o "No aplica" (comunicado oficial, bug bounty), es súper valioso tener enunciado el problema y links a las fuentes.

2018-08-13 12:36 UTC, leosoto commented on README.md
> +## 25 de Julio de 2018 - ¿Correos de Chile?
Si no sabemos el origen dejemoslo como "Desconocido". A menos que haya evidencia clara de que fue Correos (en cuyo caso le sacamos los signos de pregunta.

2018-08-13 12:36 UTC, leosoto commented on README.md
> +- **¿Hubo recompensa ("bug bounty") o reconocimiento para quien lo reportó?** No. ⚠️
- Si se trata de la filtración, entonces "No aplica" (pues no fue reportada responsablemente)

- Se se trata de la teoría del bug de correos, falta ver si realmente allá surgió la filtración.

2018-08-13 12:36 UTC, leosoto commented on README.md
> +- **Reportado por**: Fernando Lagos (@Zerial en Twitter)
La filtración como tal fue reportada (irresponsablemente) por [la cuenta twitter que dice ser de Shadow Brokers y que ha sido suspendida](https://twitter.com/brokers_shadow). 

La teoría de que es correos el origen del problema entiendo que es de @adderou a juzgar [por lo que veo en tus fuentes](https://www.reddit.com/r/chile/comments/91yz9i/pregunta_a_afectados_por_filtraci%C3%B3n_de_tarjetas/).

2018-08-13 12:36 UTC, leosoto commented on README.md
> +- **Comunicado oficial de la empresa**: Correos de Chile confirma que la filtración de números de tarjetas "no tendría relación con los sistemas de Correos".  Esto, tras hacer "los análisis y revisio
Ante tal comunicado necesitaríamos pruebas super claras de que realmente el problema es de correos

2018-08-13 12:36 UTC, leosoto commented on README.md
> +- **Impacto**: Los datos contienen toda la información necesaria para realizar una compra.
Yo agregaría "en canales que no solicitan una autenticación con el banco emisor, como compras internacionales o telefónicas"

2018-08-13 12:36 UTC, leosoto commented on README.md
> +  - [Segundo comunicado acerca del incidente de seguridad de tarjetas de crédito(SBIF)](www.sbif.cl/sbifweb/servlet/Noticia?indice=2.1&idContenido=12161)
Ya que linkeas al segundo comunicado, sería bueno linkear al primero

2018-08-15 20:10 UTC, leosoto approved these changes
Se ve bien, lo voy a mezclar!

2018-08-15 20:10 UTC, merged

2018-08-15 20:11 UTC, paparga commented
Me quedó una duda con esta noticia: [Incidente de seguridad relacionado con información de tarjetas de crédito](http://www.sbif.cl/sbifweb/servlet/Noticia?indice=2.1&idContenido=12162) habría que agregarla a las fuentes o no?

2018-08-15 20:12 UTC, paparga commented
Disculpa copié el titulo mal.... 
[SBIF presenta denuncia en la Fiscalía Centro Norte por incidente de seguridad de tarjetas de crédito](http://www.sbif.cl/sbifweb/servlet/Noticia?indice=2.1&idContenido=12162)

2018-08-15 20:18 UTC, leosoto commented
@paparga Sí, sería algo útil de agregar a las fuentes. Ya mezclé este PR, así que tendrías que hacer otro :)